# Generated by Django 6.0 on 2025-12-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('race', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('age_group', models.CharField(max_length=20)),
                ('hospital_stay', models.IntegerField()),
                ('hba1c', models.CharField(max_length=20)),
                ('diabetes_med', models.BooleanField()),
                ('admit_source', models.CharField(max_length=20)),
                ('patient_visits', models.IntegerField()),
                ('num_medications', models.IntegerField()),
                ('num_diagnosis', models.IntegerField()),
                ('insulin_level', models.CharField(max_length=20)),
                ('readmitted', models.BooleanField()),
            ],
        ),
    ]
